import React from 'react'
import ScheduleRow from './ScheduleRow'
import { Table } from 'react-bootstrap'

const Schedules = ( props ) => {
	return (<>
		<Table className="schedules__table mb-0" striped bordered>
			<thead>
				<tr>
					<th>#</th>
					<th className="schedules__signature">Pracownik</th>
					<th>Godz.</th>
					<th>Dw.</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th>1</th>
					<td>Ada</td>
					<td>196</td>
					<td>?</td>
					<td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td>
				</tr>

				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
				<tr> <th>1</th> <td>Ada</td> <td>196</td> <td>?</td> <td className="text-nowrap">aASDSA DSAD ASD AASD ASD ASD ASD AS DSAD ASD ASD SA DSAD SADSAD SAD SA DASDSAD SADSAD SADSADSADSADSADSAFSAFSAFASFSDSA DSAD SAD SAD SAD ASD SAD SAD SAD SAD ASD SAD SADS ASA D SSA DSA DSAD</td> </tr>
			</tbody>
		</Table>
	</>)
}

export default Schedules
